"""initial city schema

Revision ID: 4ba39834e3dd
Revises: 
Create Date: 2026-09-01 00:05:04.308157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba39834e3dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('city_level', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('concern', sa.String(length=48), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('severity_at_review', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_world_decisions_world_decision', ['world_id', 'decision_id'], unique=True)

    op.create_table('world_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.create_index('ix_world_events_world_day', ['world_id', 'day'], unique=False)
        batch_op.create_index('ix_world_events_world_event', ['world_id', 'event_id'], unique=True)

    op.create_table('world_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Float(), nullable=False),
    sa.Column('employment_rate', sa.Float(), nullable=False),
    sa.Column('housing_shortage', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('gdp', sa.Float(), nullable=False),
    sa.Column('approval_rating', sa.Float(), nullable=False),
    sa.Column('city_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_world_metrics_world_day', ['world_id', 'day'], unique=True)

    op.create_table('world_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_snapshots_world_id'), ['world_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_snapshots_world_id'))

    op.drop_table('world_snapshots')
    with op.batch_alter_table('world_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_world_metrics_world_day')

    op.drop_table('world_metrics')
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.drop_index('ix_world_events_world_event')
        batch_op.drop_index('ix_world_events_world_day')

    op.drop_table('world_events')
    with op.batch_alter_table('world_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_world_decisions_world_decision')

    op.drop_table('world_decisions')
    op.drop_table('worlds')
    # ### end Alembic commands ###
